"use client"

import React, { useMemo, useState } from "react"
import { useLanguage } from "../../../components/i18n/LanguageContext"

type CleanupItem = {
  id: string
  icon: string
  title: string
  description: string
  size: number
  unit: "MB" | "GB"
}

const CLEANUP_ITEMS: CleanupItem[] = [
  {
    id: "temp",
    icon: "⌁",
    title: "Temporary Files",
    description: "Temporary files created by Windows and applications.",
    size: 1.8,
    unit: "GB",
  },
  {
    id: "cache",
    icon: "◈",
    title: "Windows Cache",
    description: "Cached system data that can be safely regenerated.",
    size: 624,
    unit: "MB",
  },
  {
    id: "shader",
    icon: "◇",
    title: "Shader Cache",
    description: "GPU shader cache used by games and graphics apps.",
    size: 412,
    unit: "MB",
  },
  {
    id: "thumbnail",
    icon: "▧",
    title: "Thumbnail Cache",
    description: "Cached image previews generated by Windows.",
    size: 95,
    unit: "MB",
  },
  {
    id: "logs",
    icon: "≡",
    title: "System Logs",
    description: "Old diagnostic and application log files.",
    size: 186,
    unit: "MB",
  },
  {
    id: "recycle",
    icon: "⌫",
    title: "Recycle Bin",
    description: "Files currently stored inside the Recycle Bin.",
    size: 2.4,
    unit: "GB",
  },
]

export default function CleanupPage() {
  const { language } = useLanguage()

  const th = language === "th"

  const [selected, setSelected] = useState<string[]>([
    "temp",
    "cache",
    "shader",
    "thumbnail",
  ])

  const [isCleaning, setIsCleaning] = useState(false)
  const [finished, setFinished] = useState(false)

  const selectedItems = useMemo(
    () =>
      CLEANUP_ITEMS.filter((item) =>
        selected.includes(item.id)
      ),
    [selected]
  )

  const totalMB = useMemo(() => {
    return selectedItems.reduce((total, item) => {
      return (
        total +
        (item.unit === "GB"
          ? item.size * 1024
          : item.size)
      )
    }, 0)
  }, [selectedItems])

  const totalDisplay =
    totalMB >= 1024
      ? `${(totalMB / 1024).toFixed(2)} GB`
      : `${Math.round(totalMB)} MB`

  function toggle(id: string) {
    setFinished(false)

    setSelected((current) =>
      current.includes(id)
        ? current.filter((item) => item !== id)
        : [...current, id]
    )
  }

  function selectAll() {
    setFinished(false)
    setSelected(CLEANUP_ITEMS.map((item) => item.id))
  }

  function clearAll() {
    setFinished(false)
    setSelected([])
  }

  async function startCleanup() {
    if (!selected.length || isCleaning) return

    setIsCleaning(true)
    setFinished(false)

    await new Promise((resolve) =>
      setTimeout(resolve, 1400)
    )

    setIsCleaning(false)
    setFinished(true)
  }

  return (
    <section className="cleanup-page">

      {/* HEADER */}

      <header className="cleanup-header">

        <div>
          <div className="cleanup-kicker">
            WOS / TOOLS / CLEANUP
          </div>

          <h1>
            {th
              ? "ทำความสะอาดระบบ"
              : "System Cleanup"}
          </h1>

          <p>
            {th
              ? "ลบไฟล์ที่ไม่จำเป็นและเพิ่มพื้นที่ว่างให้ระบบ"
              : "Remove unnecessary files and free up storage space."}
          </p>
        </div>

        <div className="cleanup-ready">
          <span />
          {th ? "ระบบพร้อม" : "SYSTEM READY"}
        </div>

      </header>

      {/* SUMMARY */}

      <div className="cleanup-summary">

        <div className="cleanup-summary-left">

          <div className="cleanup-summary-icon">
            ✦
          </div>

          <div>
            <span className="cleanup-summary-label">
              {th ? "พื้นที่ที่เลือก" : "SELECTED SPACE"}
            </span>

            <strong>
              {totalDisplay}
            </strong>

            <small>
              {selected.length} / {CLEANUP_ITEMS.length}{" "}
              {th ? "รายการ" : "items selected"}
            </small>
          </div>

        </div>

        <div className="cleanup-summary-actions">

          <button
            type="button"
            onClick={selectAll}
          >
            {th ? "เลือกทั้งหมด" : "Select All"}
          </button>

          <button
            type="button"
            onClick={clearAll}
          >
            {th ? "ล้างการเลือก" : "Clear"}
          </button>

        </div>

      </div>

      {/* TARGETS */}

      <div className="cleanup-section">

        <div className="cleanup-section-head">

          <div>
            <span>
              CLEANUP TARGETS
            </span>

            <h2>
              {th
                ? "รายการทำความสะอาด"
                : "Cleanup Targets"}
            </h2>
          </div>

          <div className="cleanup-counter">
            {selected.length}/{CLEANUP_ITEMS.length}
          </div>

        </div>

        <div className="cleanup-grid">

          {CLEANUP_ITEMS.map((item) => {

            const active =
              selected.includes(item.id)

            return (
              <button
                key={item.id}
                type="button"
                className={`cleanup-card ${
                  active ? "is-selected" : ""
                }`}
                onClick={() => toggle(item.id)}
              >

                <div className="cleanup-card-top">

                  <div className="cleanup-item-icon">
                    {item.icon}
                  </div>

                  <div
                    className={`cleanup-check ${
                      active ? "checked" : ""
                    }`}
                  >
                    {active ? "✓" : ""}
                  </div>

                </div>

                <h3>
                  {th
                    ? item.id === "temp"
                      ? "ไฟล์ชั่วคราว"
                      : item.id === "cache"
                        ? "Windows Cache"
                        : item.id === "shader"
                          ? "Shader Cache"
                          : item.id === "thumbnail"
                            ? "Thumbnail Cache"
                            : item.id === "logs"
                              ? "System Logs"
                              : "Recycle Bin"
                    : item.title}
                </h3>

                <p>
                  {th
                    ? item.id === "temp"
                      ? "ไฟล์ชั่วคราวจาก Windows และโปรแกรมต่าง ๆ"
                      : item.id === "cache"
                        ? "ข้อมูล Cache ที่ระบบสามารถสร้างใหม่ได้"
                        : item.id === "shader"
                          ? "Cache ของ GPU สำหรับเกมและกราฟิก"
                          : item.id === "thumbnail"
                            ? "ภาพตัวอย่างที่ Windows สร้างไว้"
                            : item.id === "logs"
                              ? "ไฟล์ Log เก่าของระบบและโปรแกรม"
                              : "ไฟล์ที่อยู่ในถังรีไซเคิล"
                    : item.description}
                </p>

                <div className="cleanup-item-size">
                  <span>
                    {th ? "ขนาด" : "SIZE"}
                  </span>

                  <b>
                    {item.size} {item.unit}
                  </b>
                </div>

              </button>
            )
          })}

        </div>

      </div>

      {/* BOTTOM ACTION */}

      <div className="cleanup-bottom">

        <div className="cleanup-status">

          <div
            className={`cleanup-status-icon ${
              finished ? "done" : ""
            }`}
          >
            {finished ? "✓" : "●"}
          </div>

          <div>
            <strong>
              {isCleaning
                ? th
                  ? "กำลังทำความสะอาด..."
                  : "Cleaning system..."
                : finished
                  ? th
                    ? "ทำความสะอาดเสร็จแล้ว"
                    : "Cleanup complete"
                  : th
                    ? "พร้อมทำความสะอาด"
                    : "Ready to clean"}
            </strong>

            <span>
              {isCleaning
                ? th
                  ? "กำลังประมวลผลรายการที่เลือก"
                  : "Processing selected targets"
                : finished
                  ? th
                    ? "การทำงานเสร็จสมบูรณ์"
                    : "Operation completed successfully"
                  : th
                    ? "เลือกสิ่งที่ต้องการลบแล้วกดเริ่ม"
                    : "Select targets and start cleanup"}
            </span>
          </div>

        </div>

        <button
          type="button"
          className="cleanup-start"
          disabled={
            !selected.length || isCleaning
          }
          onClick={startCleanup}
        >
          {isCleaning
            ? th
              ? "กำลังทำความสะอาด..."
              : "Cleaning..."
            : finished
              ? th
                ? "ทำอีกครั้ง"
                : "Run Again"
              : th
                ? "เริ่มทำความสะอาด"
                : "Start Cleanup"}
        </button>

      </div>

    </section>
  )
      }
