"use client"

import React, { useMemo, useState } from "react"

type CleanupTarget = {
  id: string
  icon: string
  title: string
  description: string
  size: string
  sizeMb: number
  recommended?: boolean
}

const TARGETS: CleanupTarget[] = [
  {
    id: "temp",
    icon: "⌁",
    title: "Temporary Files",
    description:
      "Temporary files created by Windows and applications.",
    size: "1.8 GB",
    sizeMb: 1843,
    recommended: true,
  },
  {
    id: "windows-cache",
    icon: "◈",
    title: "Windows Cache",
    description:
      "Cached system data that can be safely regenerated.",
    size: "624 MB",
    sizeMb: 624,
    recommended: true,
  },
  {
    id: "shader",
    icon: "◇",
    title: "Shader Cache",
    description:
      "GPU shader cache used by games and graphics apps.",
    size: "412 MB",
    sizeMb: 412,
    recommended: true,
  },
  {
    id: "thumbnail",
    icon: "▧",
    title: "Thumbnail Cache",
    description:
      "Cached image previews generated by Windows.",
    size: "95 MB",
    sizeMb: 95,
    recommended: true,
  },
  {
    id: "logs",
    icon: "≡",
    title: "System Logs",
    description:
      "Old diagnostic and application log files.",
    size: "186 MB",
    sizeMb: 186,
  },
  {
    id: "recycle",
    icon: "⌫",
    title: "Recycle Bin",
    description:
      "Files currently stored inside the Recycle Bin.",
    size: "2.4 GB",
    sizeMb: 2458,
  },
]

export default function CleanupPage() {
  const [selected, setSelected] = useState<string[]>(
    TARGETS
      .filter((item) => item.recommended)
      .map((item) => item.id)
  )

  const [cleaning, setCleaning] = useState(false)
  const [completed, setCompleted] = useState(false)

  const selectedItems = useMemo(
    () =>
      TARGETS.filter((item) =>
        selected.includes(item.id)
      ),
    [selected]
  )

  const selectedSize = useMemo(() => {
    const mb = selectedItems.reduce(
      (total, item) => total + item.sizeMb,
      0
    )

    if (mb >= 1024) {
      return `${(mb / 1024).toFixed(2)} GB`
    }

    return `${mb} MB`
  }, [selectedItems])

  function toggleTarget(id: string) {
    setSelected((current) =>
      current.includes(id)
        ? current.filter((item) => item !== id)
        : [...current, id]
    )

    setCompleted(false)
  }

  function selectAll() {
    setSelected(TARGETS.map((item) => item.id))
    setCompleted(false)
  }

  function clearSelection() {
    setSelected([])
    setCompleted(false)
  }

  function startCleanup() {
    if (selected.length === 0 || cleaning) return

    setCleaning(true)

    window.setTimeout(() => {
      setCleaning(false)
      setCompleted(true)
      setSelected([])
    }, 1200)
  }

  return (
    <div className="wos-page-transition wos-cleanup-page">

      {/* =====================================================
          HEADER
          ===================================================== */}

      <header className="wos-cleanup-header">

        <div>
          <div className="wos-cleanup-kicker">
            TOOLS / SYSTEM CLEANUP
          </div>

          <div className="wos-cleanup-title-row">
            <h1>System Cleanup</h1>

            <span className="wos-cleanup-badge">
              SAFE MODE
            </span>
          </div>

          <p>
            Remove unnecessary files and free up
            storage space.
          </p>
        </div>

        <div className="wos-cleanup-ready">
          <span />
          SYSTEM READY
        </div>

      </header>

      {/* =====================================================
          SUMMARY
          ===================================================== */}

      <section className="wos-cleanup-summary">

        <div className="wos-cleanup-summary-left">

          <div className="wos-cleanup-summary-icon">
            ✦
          </div>

          <div>
            <span className="wos-cleanup-summary-label">
              SELECTED SPACE
            </span>

            <strong>
              {selectedSize}
            </strong>
          </div>

        </div>

        <div className="wos-cleanup-summary-right">

          <div className="wos-cleanup-count">
            <strong>
              {selected.length}
            </strong>

            <span>
              / {TARGETS.length}
            </span>

            <small>items selected</small>
          </div>

          <div className="wos-cleanup-actions">
            <button
              type="button"
              onClick={selectAll}
              className="wos-cleanup-text-button"
            >
              Select All
            </button>

            <button
              type="button"
              onClick={clearSelection}
              className="wos-cleanup-text-button muted"
            >
              Clear
            </button>
          </div>

        </div>

      </section>

      {/* =====================================================
          TARGET HEADER
          ===================================================== */}

      <div className="wos-cleanup-section-header">

        <div>
          <span>CLEANUP TARGETS</span>

          <h2>Cleanup Targets</h2>
        </div>

        <div className="wos-cleanup-progress">
          <strong>
            {selected.length}
          </strong>

          <span>
            /{TARGETS.length}
          </span>
        </div>

      </div>

      {/* =====================================================
          TARGET GRID
          ===================================================== */}

      <section className="wos-cleanup-grid">

        {TARGETS.map((target) => {
          const active = selected.includes(target.id)

          return (
            <button
              type="button"
              key={target.id}
              onClick={() => toggleTarget(target.id)}
              className={`wos-cleanup-card ${
                active ? "selected" : ""
              }`}
            >

              <div className="wos-cleanup-card-top">

                <div className="wos-cleanup-card-icon">
                  {target.icon}
                </div>

                <div
                  className={`wos-cleanup-check ${
                    active ? "checked" : ""
                  }`}
                >
                  {active ? "✓" : ""}
                </div>

              </div>

              <div className="wos-cleanup-card-body">

                <h3>
                  {target.title}
                </h3>

                <p>
                  {target.description}
                </p>

              </div>

              <div className="wos-cleanup-card-footer">

                <span>SIZE</span>

                <strong>
                  {target.size}
                </strong>

              </div>

            </button>
          )
        })}

      </section>

      {/* =====================================================
          BOTTOM ACTION
          ===================================================== */}

      <section className="wos-cleanup-bottom">

        <div className="wos-cleanup-status">

          <div className="wos-cleanup-status-dot">
            <span />
          </div>

          <div>
            <strong>
              {completed
                ? "Cleanup completed"
                : cleaning
                ? "Cleaning system..."
                : selected.length > 0
                ? "Ready to clean"
                : "No targets selected"}
            </strong>

            <p>
              {completed
                ? "Selected cleanup targets have been processed."
                : selected.length > 0
                ? "Select targets and start cleanup"
                : "Select at least one cleanup target"}
            </p>
          </div>

        </div>

        <button
          type="button"
          onClick={startCleanup}
          disabled={
            selected.length === 0 ||
            cleaning
          }
          className="wos-cleanup-start"
        >
          {cleaning
            ? "Cleaning..."
            : completed
            ? "Cleanup Complete"
            : "Start Cleanup"}
        </button>

      </section>

    </div>
  )
    }
